### ISSUE TITLE
Split up library into core and prometheus

### ISSUE THREAD

**Issue by sattvik** [MonsantoCo/kamon-prometheus#1]
In the future, it may be desirable to use the Kamon -> Prometheus mapping logic without the Spray endpoint, e.g. to create a Play endpoint.  As such the library should be split up into kamon-prometheus-core and kamon-prometheus-spray.

**Comment by maesenka** [comment]
+1

**Comment by sattvik** [comment]
In the end, I decided not to split the library apart.  Instead, Spray (and Akka HTTP) are now optional dependencies.  You can use the library without pulling in what you don't need.  This approach is a little easier to manage than having multiple libraries.
