### ISSUE TITLE
Play framework endpoint

### ISSUE THREAD

**Issue by jaroslawZawila** [MonsantoCo/kamon-prometheus#15]
Hey. I have just wonder if there is any easy way to add endpoint for play framework. Alternatively if there is any example how expose metrics manually by using play ?

**Comment by pjfanning** [comment]
This might help: https://gist.github.com/timohirt/3836b6b875dfcf912a36

**Comment by mirkof** [comment]
This is my solution (with this library, not the default java client one):
https://gist.github.com/mirkof/821fda02976916f43acd4338de82c4fd
