### ISSUE TITLE
Support Akka-http aswell?

### ISSUE THREAD

**Issue by Fristi** [MonsantoCo/kamon-prometheus#5]
Would be great to support akka-http aswell next to Spray.

**Comment by wlk** [comment]
Is there any progress on this issue? Akka-http is getting more widespread adoption now

**Comment by sattvik** [comment]
For the 0.2.0 release, I am going to decouple the metrics gathering part of the extension with the part that is used for publishing the metrics.  I cannot promise that this will be done this week, but it should be fairly easy to do it.

**Comment by sattvik** [comment]
Check out [AkkaHttpEndpoint](http://monsantoco.github.io/kamon-prometheus/api/0.2.0/#com.monsanto.arch.kamon.prometheus.akka_http.AkkaHttpEndpoint) in the fresh 0.2.0 release.
