### ISSUE TITLE
Incompatible with Kamon 0.6.0

### ISSUE THREAD

**Issue by sjoerdmulder** [MonsantoCo/kamon-prometheus#6]
Hi,

The `Kamon.apply(key: ExtensionId)` method has been removed. So we cannot expose the route easily anymore. 

Any workaround possible?

**Comment by ivantopo** [comment]
Hello @sjoerdmulder, can you please show me where/how this was used? maybe I can help you find some workaround :)

**Comment by sjoerdmulder** [comment]
@ivantopo 
It's used to expose the `route` property as in
```
  path("metrics") {
          Kamon(Prometheus).route
   }
```

**Comment by sjoerdmulder** [comment]
The route is here:
https://github.com/MonsantoCo/kamon-prometheus/blob/master/library/src/main/scala/com/monsanto/arch/kamon/prometheus/PrometheusExtension.scala#L44

**Comment by sattvik** [comment]
I'll look into this over the weekend to see if I can get a new release out with a fix.  I do appreciate any help.  I apologise for the delay in getting this fix.

**Comment by f1yegor** [comment]
The Prometheus module is also not auto-started with version 0.6.0 of kamon

**Comment by rahilb** [comment]
I've looked into this, and IMO the cleanest way to do this is to just have the library automatically bind to a configured port, using kamon's actorsystem. IMO this is the easiest and cleanest way to support kamon 0.6.*


`Kamon.shutdown()` also no longer does anything but shutdown the kamon actor system, so this causes most of `SnapshotConverterSpec` to fail as they expect a clean kamon slate before each test.

**Comment by rahilb** [comment]
Hi on a fork i've upgraded Kamon to 0.6.2. As a result of changes in the Kamon API, i've changed this library to automatically bind the API on /metrics on a configured port. 

You can see the changes here: https://github.com/sky-uk/kamon-prometheus/pull/1

Obviously this is a breaking change...

**Comment by sattvik** [comment]
I apologise for taking so long to address this.  I am planning on getting a new release out later this week.

**Comment by sattvik** [comment]
I have now published 0.2.0 which supports Kamon 0.6.2.

**Comment by f1yegor** [comment]
Confirm. Fixed in 0.2.0. Thanks!
